[package]
name = "testenv"
version = "0.1.0"
authors = ["Vladislav Melnik <vladislav.melnik@bitfury.com>"]

[dependencies]
wire = { path = "../wire" }
brontide = { path = "../brontide" }
lnd-rust = "0.3.3"
grpc = "0.5.0"
futures = "0.1.23"
lazycell = "1.0.0"
hex = "0.3.2"
