[package]
name = "wallet"
version = "0.1.0"
authors = ["evgeniy.scherbina <evgeniy.scherbina@bitfury.com>"]

[dependencies]
bitcoin = "0.13.2"
secp256k1 = "0.9.2"
hex = "0.3.2"
wire = { path = "../wire" }
