[package]
name = "common-types"
version = "0.0.0"
authors = ["LightningPeach <contact@lightningpeach.com>"]

[dependencies]
serde = "1"
serde_derive = "1"
rand = "0.5"
sha2 = "0.7.*"
hex-literal = "0.1.1"
hex = "0.3.2"
secp256k1 = "0.9.*"

[features]
testing = []
