[package]
name = "bitcoin-types"
version = "0.0.0"
authors = ["LightningPeach <contact@lightningpeach.com>"]

[dependencies]
serde = "1"
serde_derive = "1"
rand = "0.5"
sha2 = "0.7.1"
common-types = { path = "../common-types" }
