[package]
name = "routing"
version = "0.0.0"
authors = ["LightningPeach <contact@lightningpeach.com>"]

[dependencies]
secp256k1 = "0.9.2"
wire = { path = "../wire" }
brontide = { path = "../brontide" }
common-types = { path = "../common-types" }
bitcoin-types = { path = "../bitcoin-types" }
chrono = "0.4.5"
rand = "0.5.4"
specs = "0.12.2"
specs-derive = "0.2.0"
shred = "0.7.0"
shred-derive = "0.5.0"
rayon = "1.0.2"

[dev-dependencies]
hex = "0.3.2"
hex-literal = "0.1.1"
brontide = { path = "../brontide", features = ["testing"] }
wire = { path = "../wire", features = ["testing"] }
